### ISSUE TITLE
cshtml (aspnetcorerazor) - there is no formatter for 'aspnetcorerazor' files installed

### ISSUE THREAD

**Issue by 304NotModified** [squeeble-ink/vscode.mint-it#2]
Hi,

After installing this extension, and format document, I get the error

> there is no formatter for 'aspnetcorerazor' files installed

See screenshot:
![image](https://user-images.githubusercontent.com/5808377/144048499-60dccc7f-dc22-48fc-ab39-dacc1fd97213.png)

Any idea why it isn't working?

Version 1.1.0:

![image](https://user-images.githubusercontent.com/5808377/144048644-42bd0e4d-493a-4dbc-bdfa-819c0627f06e.png)

**Comment by TessavWalstijn** [comment]
No idea! But I will look in to it!

**Comment by TessavWalstijn** [comment]
Hi do you have the [C# extension](https://marketplace.visualstudio.com/items?itemName=ms-dotnettools.csharp) installed on your vs-code?

I can't reproduce it at the moment. However I did get a popup by vs-code to install the linked extension when I uninstalled the [C# extension](https://marketplace.visualstudio.com/items?itemName=ms-dotnettools.csharp) and opened a `aspnetcorerazor` file.

Since Mint it is only a formatter for the comments within your `aspnetcorerazor` file.

**Comment by 304NotModified** [comment]
> Hi do you have the [C# extension](https://marketplace.visualstudio.com/items?itemName=ms-dotnettools.csharp) installed on your vs-code?

Yes I have. 


Steps to reproduce:

1. open a .cshtml file (not a project) in VS Code
2. do format document
![image](https://user-images.githubusercontent.com/5808377/148575984-2c9c1c90-9086-43f1-b159-f46dc5a4fbf9.png)
3. result: ![image](https://user-images.githubusercontent.com/5808377/144048499-60dccc7f-dc22-48fc-ab39-dacc1fd97213.png)

**Comment by 304NotModified** [comment]
I guess this is the confusion:

![image](https://user-images.githubusercontent.com/5808377/148577035-6faf0fc8-b14b-4307-987c-b49f226e926a.png)


I doesn't do formatting, as I see in the README. The category is confusing.  --> #3
